services:
  proxy:
    image: your-dockerhub-account/webrtc-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}

  turn:
    image: your-dockerhub-account/webrtc-turn:latest
    restart: always
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "49152-65535:49152-65535/udp"
    environment:
      - TURN_REALM=${TURN_REALM}
      - TURN_AUTH_SECRET=${TURN_AUTH_SECRET}
      - TURN_CRED_TTL=${TURN_CRED_TTL}

  signaling:
    image: ghcr.io/ale007xd/webrtc-signaling:latest
    restart: always
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - CONTACT_LIST_JSON=${CONTACT_LIST_JSON}
      - VPS_HOST=${VPS_HOST}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}

  web:
    image: ghcr.io/ale007xd/webrtc-web:latest
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}
