services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL_LETSENCRYPT=${EMAIL_LETSENCRYPT}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - letsencrypt_data:/etc/letsencrypt
      - nginx_logs:/var/log/nginx
    depends_on:
      - signaling
      - web

  turn:
    build:
      context: ./turn
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3478:3478/udp"
      - "3478:3478/tcp"
      - "5349:5349/udp"
      - "5349:5349/tcp"
      - "49152-65535:49152-65535/udp"
    environment:
      - TURN_REALM=${TURN_REALM}
      - TURN_AUTH_SECRET=${TURN_AUTH_SECRET}
      - TURN_CRED_TTL=${TURN_CRED_TTL}
      - DOMAIN=${DOMAIN}
    volumes:
      - ./turn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - turn_logs:/var/log/turn

  signaling:
    image: ghcr.io/ale007xd/webrtc-signaling:latest
    restart: always
    environment:
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - ALLOWED_USER_IDS=${ALLOWED_USER_IDS}
      - CONTACT_LIST_JSON=${CONTACT_LIST_JSON}
      - VPS_HOST=${VPS_HOST}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}
      - SIGNALING_PUBLIC_URL=${SIGNALING_PUBLIC_URL}
      - RATE_LIMITS_JSON=${RATE_LIMITS_JSON}
      - NODE_ENV=production
      - PORT=3001
    ports:
      - "3001:3001"

  web:
    image: ghcr.io/ale007xd/webrtc-web:latest
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - APP_PUBLIC_URL=${APP_PUBLIC_URL}
      - SIGNALING_PUBLIC_URL=${SIGNALING_PUBLIC_URL}
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"

volumes:
  letsencrypt_data:
  nginx_logs:
  turn_logs:

networks:
  default:
    name: webrtc-network
